### ISSUE TITLE
Hackage release?

### ISSUE THREAD

**Issue by tchoutri** [bflyblue/servant-event-stream#8]
@bflyblue Hi, thanks a lot for the work you've put into servant-event-stream! I was wondering if you had a timeline for uploading it to Hackage (mostly for online docs). 

Cheers!

**Comment by bflyblue** [comment]
I just want to bring across some tests from one of the PRs and then I'll
push it up. Hopefully this weekend!

**Comment by bflyblue** [comment]
I've pushed up 0.3.0 as is for now, the tests require client support which I will add later :)

**Comment by tchoutri** [comment]
Thank you so much!
